### ISSUE TITLE
python setup.py sdist upload breaks on Python 3

### ISSUE THREAD

**Issue by audreyfeldroy** [audreyr/complexity#1]
It's fine on Python 2, so that's what I use to upload the package to PyPI.

On Python 3, this happens:

```
$ python setup.py sdist upload
running sdist
running egg_info
writing dependency_links to complexity.egg-info/dependency_links.txt
writing complexity.egg-info/PKG-INFO
writing requirements to complexity.egg-info/requires.txt
writing top-level names to complexity.egg-info/top_level.txt
writing entry points to complexity.egg-info/entry_points.txt
reading manifest file 'complexity.egg-info/SOURCES.txt'
writing manifest file 'complexity.egg-info/SOURCES.txt'
running check
creating complexity-0.1.1
creating complexity-0.1.1/complexity
creating complexity-0.1.1/complexity.egg-info
making hard links in complexity-0.1.1...
hard linking README.rst -> complexity-0.1.1
hard linking setup.py -> complexity-0.1.1
hard linking complexity/__init__.py -> complexity-0.1.1/complexity
hard linking complexity/complexity.py -> complexity-0.1.1/complexity
hard linking complexity.egg-info/PKG-INFO -> complexity-0.1.1/complexity.egg-info
hard linking complexity.egg-info/SOURCES.txt -> complexity-0.1.1/complexity.egg-info
hard linking complexity.egg-info/dependency_links.txt -> complexity-0.1.1/complexity.egg-info
hard linking complexity.egg-info/entry_points.txt -> complexity-0.1.1/complexity.egg-info
hard linking complexity.egg-info/not-zip-safe -> complexity-0.1.1/complexity.egg-info
hard linking complexity.egg-info/requires.txt -> complexity-0.1.1/complexity.egg-info
hard linking complexity.egg-info/top_level.txt -> complexity-0.1.1/complexity.egg-info
Writing complexity-0.1.1/setup.cfg
Creating tar archive
removing 'complexity-0.1.1' (and everything under it)
running upload
Traceback (most recent call last):
  File "setup.py", line 56, in <module>
    keywords='complexity static site generator HTML Jinja2 templates S3',
  File "/usr/local/lib/python3.3/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.3/distutils/dist.py", line 917, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.3/distutils/dist.py", line 936, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.3/distutils/command/upload.py", line 66, in run
    self.upload_file(command, pyversion, filename)
  File "/usr/local/lib/python3.3/distutils/command/upload.py", line 155, in upload_file
    body.write(value)
TypeError: 'str' does not support the buffer interface
```

**Comment by 1e0ng** [comment]
Hi, would you tell me since which version it's fixed?
